# This is the configuration used to check the `favy` source code.
#
# See <https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml> for more details.

require: rubocop-rake

# === Overrides ===

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Description: 'Limit lines to 140 characters.'
  Max: 140

Lint/ScriptPermission:
  Description: 'Grant script file execute permission.'
  Enabled: false

Style/AsciiComments:
  Description: 'Use only ASCII symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false
