# This is the configuration used to check the `Favy` source code.

# Configuration
# =============

# --- Linting ---

Lint/ScriptPermission:
  Description: 'Grant script file execute permission.'
  Enabled: false

# --- Layout ---

Layout/TrailingBlankLines:
  Description: 'Checks trailing blank lines and final newline.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#newline-eof'
  Enabled: false

# --- Metrics ---

Metrics/LineLength:
  Description: 'Limit lines to 120 characters with 10 characters as buffer.'
  Max: 130

# --- Style ---

Style/AsciiComments:
  Description: 'Use only ASCII symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false