# This is the configuration used to check the `Favy` source code.

# === Overrides ===

Lint/ScriptPermission:
  Description: 'Grant script file execute permission.'
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 120 characters with 10 characters as buffer.'
  Max: 130

Style/AsciiComments:
  Description: 'Use only ASCII symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false
